language: go
dist: trusty
sudo: false

services:
 - docker

script:
 - make container
 - make test
 - e2e-tests/minikube-bootstrap.sh
 - e2e-tests/test.sh

after_success:
 - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
   echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
   make push;
   make push-head;
   fi
